### PR TITLE
Use new blockPosition method of voxel-engine

### PR DESCRIPTION
**Pull request by nakedible**
Use the new blockPosition method of voxel engine and simplify logic.

### CODE REVIEW

**Comment by max-mapper** [comment]
hmm... doesnt apply cleanly, did you merge master before making those commits?

**Comment by nakedible** [comment]
DOS newlines in index.js in master. Will rebase the changes when those have been removed.

**Comment by theoxylo** [comment]
Just saw this after I submitted my pull request. If you don't mind, I can merge these improvements into that request.

Sounds like Unix LF is also preferred, so I will do that too

**Comment by nakedible** [comment]
fine by me, thanks

**Comment by theoxylo** [comment]
I added the blockPosition usage to the other pull request, but it is commented out for now (since voxel-engine 0.10.0 is not yet published to npm that I could find).

I think the problem with this pull request is that it was based on 0.0.3 and not 0.0.4

If the other request is merged, maybe you can redo this one for full voxel-engine 0.10.0 support?

**Comment by theoxylo** [comment]
Using 0.0.5 as the base, I think this change boils down to this:

```
  var newVoxelPos = this.game.blockPosition(hit.position)
  if (   newVoxelPos[0] === this.currVoxelPos[0] 
      && newVoxelPos[1] === this.currVoxelPos[1] 
      && newVoxelPos[2] === this.currVoxelPos[2]) {
    return // voxel already highlighted, done with common case
  }
  this.mesh.position.set(newVoxelPos[0] + 0.5, newVoxelPos[1] + 0.5, newVoxelPos[2] + 0.5)
```

(and removing the old logic of course)

**Comment by nakedible** [comment]
I'll leave this in your hands, as you got the code already in, just waiting for voxel-engine 0.10.0. Thanks!

**Pull request closed without merging**
