### PR TITLE
0.0.9 - added voxel multi-select, configurable animation

### PR DESCRIPTION
**Pull request by theoxylo**
The player can now select a block of voxels by holding the 'select' key and highlighting from some start voxel (or adjacent) to an end voxel (or adjacent).

The select start and end position arrays are emitted with 2 new events:
1. 'highlight-select' (whenever the ending voxel changes)
2. 'highlight-deselect' (when the select key is released)

The voxel multi-block selection is not used for anything yet, but I am thinking of copy-paste functionality or cookie-cutter building perhaps. More demo stuff could be added to test.js, which uses voxel-hello-world (or soon will) and adds the 'K' key binding for the 'select' function.

Also, the simple animation of highlight position changes can now be specified by passing in an easing function. The default function is very simple. I think I may prefer not using the animation at all.

### CODE REVIEW

**Comment by theoxylo** [comment]
I will squash these into one commit

**Comment by theoxylo** [comment]
well that only took a couple of hours...

ready for merge now, thanks!

**Comment by max-mapper** [comment]
ohhh hell yea!!!

**Comment by max-mapper** [comment]
p.s. have you seen this canvas app i've been working on? http://maxogden.github.com/voxel-painter/

would be interested in your feedback on the keyboard shortcuts/interaction

**Comment by theoxylo** [comment]
Thanks for the merge!

Voxel painter looks very cool. Fun just to play around with making stuff (yeah bunnies). I will check it out

**Pull request merged**
