### PR TITLE
fixed raycast bug, removed legacy voxel-engine 0.3.6 support

### PR DESCRIPTION
**Pull request by theoxylo**
Now using simplified raycast approach instead of Game.prototype.raycast:

```
  // cheap raycast "lite":
  var stepDistance = 0.1
  var distanceChecked = 0
  var maxDistance = this.opts.distance || 10
  this.stepPosition.copy(this.game.cameraPosition())
  this.stepSegment.copy(this.game.cameraVector()).multiplyScalar(stepDistance)
  while (distanceChecked < maxDistance && !hit) {
    distanceChecked += stepDistance
    this.stepPosition.addSelf(this.stepSegment)
    if (this.game.voxels.voxelAtPosition(this.stepPosition)) {
      var hit = this.stepPosition
    }
  }
```

Also, using voxel size of 1 when calculating positions

### CODE REVIEW

**Comment by mikolalysenko** [comment]
Using a fixed step size won't work.  What happens if you cast a ray near the edge of a voxel?  Under this approach you'd skip the cube and right through it.  Also the latest version of voxel-raycast should fix the infinite loop bug.

**Comment by theoxylo** [comment]
@maxogden Thanks for the merge!

@mikolalysenko The fixed step size is another optimization/simplification. With a voxel size of 1 and step size of 0.1, it is pretty unusual to miss a voxel though it does happen sometimes (you have to aim just at an edge).

But I will definitely check out the updated advanced implementation in voxel-raycast. Thanks for the tip

**Comment by max-mapper** [comment]
I had to update some stuff (see https://github.com/maxogden/voxel-highlight/commit/23e021aee90d1d0a9e6e0b67792e945024b0679d) to make it work with the new voxel-engine array vector API but it works and is now back in voxel-hello-world

**Comment by mikolalysenko** [comment]
@theoxylo: A fixed step size is not an optimization.  You'll do on average 17x more work than walking the correct size, and on top of that you'll also miss voxels if you hit them at a shallow angle.

But there are issues with voxel-raycast.  I'm going to write some more thorough tests and hopefully have a validated implementation this evening.

**Comment by theoxylo** [comment]
@mikolalysenko Looks like it is working fine now. And you are right: the "simple" fixed step was far slower!

**Pull request merged**
